### ISSUE TITLE
Publish page not auth

### ISSUE THREAD

**Issue by mikbry** [Opla/front#141] opened 2018-05-22 11:02 UTC
When displaying a wrong publish page:
http://localhost:8080/publish/xxxx

It throw an error in WebService.js
![screen shot 2018-05-22 at 12 57 42](https://user-images.githubusercontent.com/395718/40358591-070ba612-5dc0-11e8-82f8-204909843364.png)
Where
isAuth = false
auth = true
And after that it disconnect from the builder on the main page.
I clean up all node_modules

<img width="475" alt="screen shot 2018-05-18 at 15 53 58" src="https://user-images.githubusercontent.com/395718/40358599-1633f4fa-5dc0-11e8-802d-81256e14a78c.png">

**Comment by lunika** [comment] 2018-05-22 12:29
ok the problem is not in the `Webservice` class IMO but in api call. `auth` should be `false`

**Comment by lunika** [comment] 2018-05-23 07:46
fixed in https://github.com/Zoapp/front/pull/60

**Closed by lunika** 2018-05-23 07:46 UTC
Labels: bug
